# Generated by Django 3.2.8 on 2024-06-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAmbiguityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.CharField(max_length=400)),
                ('ambiguity', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageCommentAmbiguityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.CharField(max_length=400)),
                ('ambiguity', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('photoalbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photoalbums.photoalbum')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photo_albums/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='photo_albums/')),
                ('description', models.CharField(max_length=4000)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('ambiguity', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photoalbums.photoalbum')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbumCommentAmbiguityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('photoalbum_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiguity_votes', to='photoalbums.photoalbumcomment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='photoalbum',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='non_empty_title_photoalbum'),
        ),
        migrations.AddField(
            model_name='imagecommentambiguityvote',
            name='image_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiguity_votes', to='photoalbums.imagecomment'),
        ),
        migrations.AddField(
            model_name='imagecomment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photoalbums.photoalbumimage'),
        ),
        migrations.AddField(
            model_name='imageambiguityvote',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiguity_votes', to='photoalbums.photoalbumimage'),
        ),
        migrations.AlterUniqueTogether(
            name='photoalbumcommentambiguityvote',
            unique_together={('ip_address', 'photoalbum_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='imagecommentambiguityvote',
            unique_together={('ip_address', 'image_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='imageambiguityvote',
            unique_together={('ip_address', 'image')},
        ),
    ]
