# Generated by Django 3.2.8 on 2024-07-16 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageambiguityvote',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecommentambiguityvote',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photoalbumcommentambiguityvote',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
