# Generated by Django 3.2.8 on 2022-01-11 20:54

from django.db import migrations, models
import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(blank=True, default=scheduling.models.current_time_with_tz, verbose_name='date created'),
        ),
    ]
