# Generated by Django 3.2.8 on 2024-06-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('article_text', models.CharField(max_length=500000)),
                ('article_text_formatted', models.CharField(max_length=500000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.CharField(max_length=400)),
                ('ambiguity', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='article_images/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommentAmbiguityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiguity_votes', to='articles.articlecomment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='non_empty_title'),
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentambiguityvote',
            unique_together={('ip_address', 'article_comment')},
        ),
    ]
