# Generated by Django 3.2.8 on 2021-11-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
