# Generated by Django 3.2.8 on 2021-11-19 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text_formatted',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
