# Generated by Django 3.2.8 on 2022-01-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20220111_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_formatted',
            field=models.CharField(max_length=500000),
        ),
    ]
