# Generated by Django 3.2.8 on 2024-07-16 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bannedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedip',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
