"""
Django settings for nitwitch project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import config
from django.core.files.storage import FileSystemStorage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY

# Application definition

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'articles.apps.ArticlesConfig',
    'photoalbums.apps.PhotoalbumsConfig',
    'adventures.apps.AdventuresConfig',
    'movienights.apps.MovienightsConfig',
    'scheduling.apps.SchedulingConfig',
    'wmvi.apps.WmviConfig',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'accounts',
    'allauth',
    'allauth.account',
    'allauth.socialaccount'
    ]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nitwitch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nitwitch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config.DB_NAME,
        'USER': config.DB_USER,
        'PASSWORD': config.DB_PASSWORD,
        'HOST': config.DB_HOST,
        'PORT': config.DB_PORT,
    },
    'movienight': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config.MOVIENIGHT_DB_NAME,
        'USER': config.MOVIENIGHT_DB_USER,
        'PASSWORD': config.MOVIENIGHT_DB_PASSWORD,
        'HOST': config.DB_HOST,
        'PORT': config.DB_PORT,
    },
}

DATABASE_ROUTERS = ['movienights.db_router.MovienightRouter']


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# USER ACC ALL-AUTH STUFF
AUTH_USER_MODEL = 'accounts.CustomUser'
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)
SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = 'index'
ACCOUNT_LOGOUT_REDIRECT_URL = 'index'


# STATIC/STORAGE
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, config.STATICFILES_LOCATION),)
# collectstatic destination (e.g. nginx alias /var/www/static). Set in config.py on prod.
STATIC_ROOT = getattr(config, 'STATIC_ROOT', None)
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
MEDIA_ROOT = os.path.join(BASE_DIR, config.MEDIAFILES_LOCATION)
# DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'
# AWS_ACCESS_KEY_ID = config.AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY = config.AWS_SECRET_ACCESS_KEY
# AWS_STORAGE_BUCKET_NAME = config.AWS_STORAGE_BUCKET_NAME
# AWS_QUERYSTRING_AUTH = False
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
# AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

if config.DEV:
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', '192.168.2.32']

    # Dev: no email step. Signup immediately creates a full admin account
    # (see accounts/signals.py). Any mail (e.g. password reset) prints to console.
    ACCOUNT_EMAIL_VERIFICATION = 'none'
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

else:
    DEBUG = False
    # Keep ddns aliases used by the home-server / DDNS entry points.
    # (www.nitiwtch.ddns.net is the historical spelling from prod — leave it.)
    ALLOWED_HOSTS = [
        'nitwitch.com',
        'www.nitwitch.com',
        'nitwitch.ddns.net',
        'www.nitwitch.ddns.net',
        'www.nitiwtch.ddns.net',
    ]
    # STATICFILES_STORAGE = 'custom_storages.StaticStorage'
    # this is a subclass of S3Boto3Storage and will route static files to the AWS static bucket

    # Prod: users must click the link in a confirmation email before they can log
    # in. New accounts are non-admin; an existing admin promotes them later.
    ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config.EMAIL_HOST
    EMAIL_PORT = config.EMAIL_PORT
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config.EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD = config.EMAIL_HOST_PASSWORD
    DEFAULT_FROM_EMAIL = config.DEFAULT_FROM_EMAIL

# Discord OAuth (Movienights viewer verification only)
DISCORD_CLIENT_ID = config.DISCORD_CLIENT_ID
DISCORD_CLIENT_SECRET = config.DISCORD_CLIENT_SECRET
DISCORD_OAUTH_REDIRECT_URI = config.DISCORD_OAUTH_REDIRECT_URI

# WMVI pipeline dashboard JSON (fixed filename; uploader overwrites in place)
WMVI_DASHBOARD_JSON_PATH = getattr(
    config,
    'WMVI_DASHBOARD_JSON_PATH',
    '/mnt/md0/nitwitch_dl/uploads/dashboard_summary.json',
)
