# Generated by Django 3.2.8 on 2024-06-08 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('view_count', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=3)),
                ('category_index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.CharField(max_length=255)),
                ('card_text', models.TextField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_cards', to='adventures.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='CardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_card_id', models.CharField(max_length=255)),
                ('option_text', models.CharField(max_length=5000)),
                ('parent_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_options', to='adventures.gamecard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='adventure',
            constraint=models.UniqueConstraint(fields=('category', 'category_index'), name='unique_category_index'),
        ),
    ]
